from turtle import begin_fill, circle, color, end_fill, forward, left, pensize, right, turtles
color ('red')
begin_fill()
pensize(3)
left(50)
forward(133)
circle(60,200)
right(140)
circle(60,200)
forward(133)
end_fill()